openapi: 3.0.1
info:
  title: Middleware
  description: Perform CRUD operations on the Knowledge Graph.
  termsOfService: https://wordlift.io/terms-of-service/
  contact:
    name: WordLift
    url: https://wordlift.io
    email: hello@wordlift.io
  license:
    name: (c) copyright 2022-present WordLift
    url: https://wordlift.io
  version: "1.0"
servers:
- url: https://api.wordlift.io/middleware
tags:
- name: Dataset
  description: Perform operations on the Knowledge Graph.
- name: Autocomplete
  description: Find entities in Linked Data or Knowledge Graph by partial match.
paths:
  /dataset/batch:
    post:
      tags:
      - Dataset
      summary: Create or update many
      description: Create or update many entities in the Knowledge Graph.
      operationId: postBatch
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
        "404":
          description: Not Found
        "401":
          description: Authentication Failure
      security:
      - ApiKey: []
  /dataset:
    post:
      tags:
      - Dataset
      summary: Create or update one
      description: Create or update an entity in the Knowledge Graph.
      operationId: post
      parameters:
      - name: uri
        in: query
        description: The entity's URI
        required: true
        schema:
          type: string
      - name: private
        in: query
        description: Whether the entity should be hidden from Linked Data and GraphQL
        required: false
        schema:
          type: boolean
          default: true
        example: true
      requestBody:
        content:
          application/ld+json: {}
        required: true
      responses:
        "200":
          description: Success
        "404":
          description: Not Found
        "401":
          description: Authentication Failure
      security:
      - ApiKey: []
    delete:
      tags:
      - Dataset
      summary: Delete one
      description: Delete an entity from the Knowledge Graph.
      operationId: delete
      parameters:
      - name: uri
        in: query
        description: The URI of the entity to delete.
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Success
        "404":
          description: Not Found
        "401":
          description: Authentication Failure
      security:
      - ApiKey: []
  /autocomplete:
    get:
      tags:
      - Autocomplete
      summary: Get
      description: The autocomplete endpoint suggests entities from Linked Data that
        match the provided query.
      operationId: get
      parameters:
      - name: query
        in: query
        description: Autocomplete query
        required: true
        schema:
          type: string
      - name: language
        in: query
        description: "2-letter language code, e.g. 'en'."
        required: true
        schema:
          type: string
      - name: scope
        in: query
        description: Scope
        required: false
        schema:
          type: string
          default: cloud
          enum:
          - cloud
      - name: limit
        in: query
        description: Maximum number of results. By default 10.
        required: false
        schema:
          type: string
          default: "10"
      - name: exclude
        in: query
        description: List of entity URIs to exclude.
        required: false
        schema:
          uniqueItems: true
          type: array
          items:
            type: string
      responses:
        "200":
          description: Success
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AutocompleteResultList'
        "404":
          description: Not Found
        "401":
          description: Authentication Failure
      security:
      - ApiKey: []
  /dataset/all:
    delete:
      tags:
      - Dataset
      summary: Delete all
      description: Delete all the entities in the Knowledge Graph.
      operationId: deleteAll
      responses:
        "200":
          description: Success
        "404":
          description: Not Found
        "401":
          description: Authentication Failure
      security:
      - ApiKey: []
components:
  schemas:
    AutocompleteResult:
      type: object
      properties:
        id:
          type: string
          format: uri
        labels:
          type: array
          items:
            type: string
        descriptions:
          type: array
          items:
            type: string
        types:
          type: array
          items:
            type: string
            format: url
        urls:
          type: array
          items:
            type: string
            format: url
        images:
          type: array
          description: A list of image URLs.
          items:
            type: string
            description: A list of image URLs.
            format: url
        sameAss:
          type: array
          items:
            type: string
            format: url
        scope:
          type: string
          enum:
          - local
          - network
          - cloud
        description:
          type: string
        mainType:
          type: string
          description: Schema type slug
        label:
          type: string
        value:
          type: string
        displayTypes:
          type: string
      description: A list of autocomplete results.
    AutocompleteResultList:
      type: array
      properties:
        empty:
          type: boolean
      description: A list of autocomplete results.
      items:
        $ref: '#/components/schemas/AutocompleteResult'
  securitySchemes:
    ApiKey:
      type: apiKey
      description: "`Key {your key}`"
      name: Authorization
      in: header
