openapi: 3.0.0
info:
  title: WordLift Sitemap Generator API
  version: 1.0.0
  description: Generate a sitemap from a GraphQL query to a WordLift Knowledge Graph.
paths:
  /sitemap/generator:
    post:
      summary: Generate Sitemap
      description: Generates a sitemap from a GraphQL query to a WordLift Knowledge Graph.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  example: "{ foodEstablishments { name: string(name: \"schema:name\") url: string(name: \"schema:url\") }}"
                operationName:
                  type: string
                  example: "Operations"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  sitemap:
                    type: string
                    description: The generated sitemap in XML format.
        '401':
          description: Unauthorized
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      security:
        - apiKeyAuth: []
components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
