name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Node deps
        run: npm install
      - name: Rebuild 'analysis' API docs
        run: npm run docusaurus clean-api-docs analysis && npm run docusaurus gen-api-docs analysis
      - name: Rebuild 'classification' API docs
        run: npm run docusaurus clean-api-docs classification && npm run docusaurus gen-api-docs classification
      - name: Rebuild 'content-generation' API docs
        run: npm run docusaurus clean-api-docs content-generation && npm run docusaurus gen-api-docs content-generation
      - name: Rebuild 'events' API docs
        run: npm run docusaurus clean-api-docs events && npm run docusaurus gen-api-docs events
      - name: Rebuild 'graphql' API docs
        run: npm run docusaurus clean-api-docs graphql && npm run docusaurus gen-api-docs graphql
      - name: Rebuild 'inspector' API docs
        run: npm run docusaurus clean-api-docs inspector && npm run docusaurus gen-api-docs inspector
      - name: Rebuild 'long-tail' API docs
        run: npm run docusaurus clean-api-docs long-tail && npm run docusaurus gen-api-docs long-tail
      - name: Rebuild 'manager' API docs
        run: npm run docusaurus clean-api-docs manager && npm run docusaurus gen-api-docs manager
      - name: Rebuild 'middleware' API docs
        run: npm run docusaurus clean-api-docs middleware && npm run docusaurus gen-api-docs middleware
      - name: Rebuild 'sitemap-generator' API docs
        run: npm run docusaurus clean-api-docs sitemap-generator && npm run docusaurus gen-api-docs sitemap-generator
      - name: Rebuild 'summarizer' API docs
        run: npm run docusaurus clean-api-docs summarizer && npm run docusaurus gen-api-docs summarizer

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_PEBBLE_0CF31410F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_PEBBLE_0CF31410F }}
          action: "close"

  run_docsearch:
    needs: ["build_and_deploy_job"]
    runs-on: ubuntu-latest
    name: Run DocSearch
    steps:
      - 
        name: Indexing
        run: docker run -e "APPLICATION_ID=${{secrets.APPLICATION_ID}}" -e "API_KEY=${{secrets.API_KEY}}" -e "CONFIG={\"index_name\":\"docs_wordlift_io\",\"start_urls\":[\"https://docs.wordlift.io\"],\"selectors\":{\"lvl0\":\"article h1\",\"lvl1\":\"article h2\",\"lvl2\":\"article h3\",\"lvl3\":\"article h4\",\"lvl4\":\"article h5\",\"lvl5\":\"article h6\",\"text\":\"article p\"}}" algolia/docsearch-scraper:v1.16.0
